{"name": "test_get_user_orders_invalid_token", "status": "broken", "statusDetails": {"message": "TypeError: get_user_orders() takes 1 positional argument but 2 were given", "trace": "self = <tests.test_user_orders.TestUserOrders object at 0x00000182FE9BE0A0>, api_client = <utils.api_client.APIClient object at 0x00000182FE961E50>\ninvalid_token = 'invalid_token'\n\n    def test_get_user_orders_invalid_token(self, api_client, invalid_token):\n        \"\"\"Тест для получения заказов с невалидным токеном\"\"\"\n>       res = api_client.get_user_orders(invalid_token)\nE       TypeError: get_user_orders() takes 1 positional argument but 2 were given\n\ntests\\test_user_orders.py:55: TypeError"}, "description": "Тест для получения заказов с невалидным токеном", "start": 1744991683590, "stop": 1744991683591, "uuid": "c0914cc6-d07f-435c-8c0a-ac2f724b72f4", "historyId": "0046048e082c8126976a9048a872d655", "testCaseId": "0046048e082c8126976a9048a872d655", "fullName": "tests.test_user_orders#test_get_user_orders_invalid_token", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user_orders"}, {"name": "subSuite", "value": "TestUserOrders"}, {"name": "host", "value": "DESKTOP-U9HTL48"}, {"name": "thread", "value": "39648-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user_orders"}]}